package com.vistony.salesforce.Entity;

public class SesionEntity {
    public static String compania_id="";
    public static String fuerzatrabajo_id="";
    public static String nombrecompania="";
    public static String nombrefuerzadetrabajo="";
    public static String nombreusuario="";
    public static String imei="";
    public static String usuario_id="";
    public static String recibo="";
    public static String imagen="";
    public static String loginSesion="0";
    public static String listaConsDeposito="0";
    public static String pagodirecto="";
    public static String serialnumber="";
    public static int resultado=0;
    public static String planta_id="";
    public static String almacen_id="";
    public static String perfil_id="";
    public static String pagopos="0";
    public static String cogsacct="";
    public static String u_vist_ctaingdcto="";
    public static String documentsowner="";
    public static String U_VIST_SUCUSU="";
    public static String CentroCosto="";
    public static String UnidadNegocio="";
    public static String LineaProduccion="";
    public static String Impuesto_ID="";
    public static String Impuesto="";
    public static String contado="";
    public static String U_VIS_CashDscnt="";
    public static String FLAG_STOCK="";
    public static String FLAG_BACKUP="";
    public static String quotation="N";
    public static String rate="0";
    public static String TipoListaPrecio="";
    public static String Print="";
    public static String activecurrency="";
    public static String flagquerystock ="N";
    public static String formhabilPrint ="N";
    public static String TipoCompra ="";
    public static String phone ="";
    public static String maxDateDeposit ="";
    public static String collectioncheck ="N";
    public static String currency ="";
    public static String updateclient ="N";
    public static String migratequotation ="N";
    public static String census ="N";
    public static String collection_salesperson ="N";
    public static String deliverydateauto="N";
    public static String currency_id="";
    public static String flagquerystockPromotion ="N";
    public static String deliveryrefusedmoney ="N";
    public static String status ="";
    public static String sendvisits ="";
    public static String sendvalidations ="";

}

